function output = getConstantTagValues(type)
switch type
    %NOTE: I tried to alphabatize these for speed ...
    case 'timestamp'
        output = {'CreateTime' 'STLiveTimestamp' 'Timestamp'};
    case 'id'
        output        = {'ActiveElectrode','ActiveLayout','ActiveWaveformObjId',...
            'BaselineSetId','Clone','From','FromDef','GroupDef','GroupId',...
            'GroupObjId','ID','Id','MaacsGroupId','MaacsTraceId','MontageChanId',...
            'OChanId','Parent','RawSweepSetId','RefElectrode','SetObjId',...
            'TestObjId','TimelineID','To','ToDef','TraceID','TraceObjId','TriggerSource'};
    case 'double'
        output = {'2ndPulseIntensity' 'AlarmLevel' 'AllowedCrossTalkRatio' ...
            'AllowedDCOffset' 'AllowedDeviationPercent' ...
            'AllowedNoiseLevel' 'AlphaMax' 'AlphaMin' ...
            'AppliedHWFilterHFF' 'AppliedHWFilterLFF' 'BetaMax' 'BetaMin' ...
            'CaptureThreshold' 'CreationTime' 'Delay' 'DeltaMax' ...
            'DeltaMin' 'Duration' 'Epoch' 'EventThreshold' 'HardwareLFF' ...
            'Height' 'HeightFraction' 'HffCutoff' 'HighFreq' ...
            'InitIntensity' 'Intensity' 'InterPulseDuration' ...
            'LatencyFrom' 'LatencyTo' 'LeftDisplayGain' 'LffCutoff' ...
            'LowFreq' 'MaskIntensity' 'MaxUserVariation' ...
            'MinCrossTalkRatio' 'ModificationTime' 'NegAlarmLevel' ...
            'NotchCutoff' 'OriginalSampFreq' 'Patient Room Time In' ...
            'PreTriggerTriggerDelay' 'PrimingGap' 'PulseDuration' ...
            'PulseIntensity' 'Range' 'Rate' 'ReferenceSignalFrequency' ...
            'ReferenceSignalP2P' 'RightDisplayGain' 'SampFreq' ...
            'SamplingFreq' 'SavedStimIntensity' 'SpectralEdge' ...
            'SquelchThreshold' 'ThetaMax' 'ThetaMin' 'ThresholdDelay' ...
            'Timebase' 'TrainRate' 'TriggerDelay' 'TriggerToStimLat' ...
            'Weight' 'WidthFraction' 'XFraction' 'YFraction'};
    case 'integer'
        output = {'AlarmInPrcnt' ...
            'AreaType' 'AudStimOutput' 'AudioOnset' 'AudioRamp' ...
            'AudioVolume' 'Baseline' 'BoardRevision' 'CaptureEnable' ...
            'CollectMaxData' 'Color' 'Colour' 'CommChannelHandle' ...
            'ConstVoltage' 'ContraMode' 'CyclingPeriod' 'Day' 'Delay' ...
            'DesiredUpdateInterval' 'DeviceType' 'DiscreteReadings' ...
            'DisplayMode' 'DisplayType' 'Divisions' 'EMGCableMode' ...
            'FWaveFilter' 'FilteringStyle' 'ForceFixChanMap' ...
            'ForcedDecimation' 'HBType' 'HardwareConfig' 'Height' ...
            'HeightFeet' 'HeightInches' 'Horizontal' 'Hour' ...
            'IOMLocalObject' 'IOMUIVersionHigh' 'IOMUIVersionLow' 'Index' ...
            'IpsiMode' 'IsActive' 'IsActiveHigh' 'IsAlarmedWave' ...
            'IsCaptured' 'IsChannelEnabled' 'IsChannelTrigger' ...
            'IsCrossTalkTest' 'IsEMGTest' 'IsEegGroup' 'IsEnabled' ...
            'IsManufacturingTest' 'IsMarker' 'IsNew' 'IsOutput' ...
            'IsPaused' 'IsRejectionOnStimSaturation' 'IsRoot' 'IsRunning' ...
            'IsSquelch' 'IsWaiting' 'LimitedHBDecimation' 'Location' ...
            'LogicalChan' 'MeClone' 'Minute' 'Mode' 'Month' 'NumAccepted' ...
            'NumDivisionsToCollect' 'NumRejected' 'NumberOfPhases' ...
            'OldLogChan' 'OnTimeline' 'Order' 'OriginX' 'OriginY' ...
            'OriginalDecim' 'PhysElectrode' 'PhysNum' 'Placement' ...
            'Polarity' 'PreTriggerDCOffset' 'PrimingPulses' 'ProcessId' ...
            'ProductVersionHigh' 'ProductVersionLow' 'PulsesPerTrain' ...
            'Reference' 'RejectionOriginator' 'RelayPort' ...
            'RelaySwitchDelay' 'Resolution' 'RestartDelay' ...
            'RollingWindow' 'STLiveNumAccepted' 'Schema' 'SequenceNumber' ...
            'SetNumber' 'ShowLiveTriggered' 'SignalType' 'SimulationMode' ...
            'SmoothSel' 'SpecDecimation' 'SpecNumBins' 'SpecResolution' ...
            'SpecType' 'SpecialType' 'StartOnTestActivation' 'State' ...
            'StimboxConnected' 'Style' 'SwStimId' 'SweepsPerAvg' ...
            'TestSetObjCount' 'TrueDifferential' 'Type' 'UseType' ...
            'ValueType' 'Visible' 'VisiblePlacementOnly' 'VisualField' ...
            'VisualFlash' 'VisualStimOutput' 'VisualTrigger' ...
            'WasBaseline' 'Width' 'X' 'Y' 'Year'};
end


end