classdef auditory < epworks.type
    %
    %
    %   Class:
    %       epworks.type.auditory
    %
    %   Not yet implemented ...
    
% '000'
% '001'
% '002'
% '003'
% '004'
% '005'
% '006'
% '007'
% '008'
% '009'
% '010'
% '011'
% '012'
% '013'
% '014'
% '015'
% '016'
% '017'
% '018'
% '019'
% '020'
% '021'
% '022'
% '023'
% '024'
% '025'
% '026'
% '027'
% '028'
% '029'
% '030'
% '031'
% '032'
% '033'
% '034'
% '035'
% 'ActiveElectrode'
% 'AllowedCrossTalkRatio'
% 'AllowedDCOffset'
% 'AllowedDeviationPercent'
% 'AllowedNoiseLevel'
% 'AudStimOutput'
% 'AudioOnset'
% 'AudioRamp'
% 'AudioVolume'
% 'BetaMax'
% 'BetaMin'
% 'CSASpectralEegView'
% 'CaptureChime'
% 'CaptureEnable'
% 'CaptureThreshold'
% 'CollectMaxData'
% 'Color'
% 'ContraMode'
% 'CyclingPeriod'
% 'Delay'
% 'DeltaMax'
% 'DeltaMin'
% 'DesiredUpdateInterval'
% 'DiscreteReadings'
% 'DisplayMode'
% 'Duration'
% 'EEGSiteGUID'
% 'EMGCableMode'
% 'EegWaveformView'
% 'Electrodes'
% 'ElementLayouts'
% 'Elements'
% 'Epoch'
% 'EventThreshold'
% 'FWaveFilter'
% 'FileName'
% 'FilteringStyle'
% 'ForceFixChanMap'
% 'ForcedDecimation'
% 'From'
% 'FullScreen'
% 'GroupDef'
% 'GroupDirView'
% 'Guid'
% 'HBType'
% 'HardwareConfig'
% 'HardwareLFF'
% 'Height'
% 'HeightFraction'
% 'HffCutoff'
% 'HistorySets'
% 'HistoryTrace0'
% 'HistoryTrace1'
% 'HistoryTrace2'
% 'HistoryTrace3'
% 'HistoryView'
% 'Horizontal'
% 'IChans'
% 'ID'
% 'IpsiMode'
% 'IsChannelEnabled'
% 'IsChannelTrigger'
% 'IsCrossTalkTest'
% 'IsEMGTest'
% 'IsEegGroup'
% 'IsManufacturingTest'
% 'IsRejectionOnStimSaturation'
% 'IsSquelch'
% 'LeftDisplayGain'
% 'LffCutoff'
% 'LimitedHBDecimation'
% 'Location'
% 'LogicalChan'
% 'MaacsGroupId'
% 'MaacsTraceId'
% 'ManufacturingTest'
% 'MaskIntensity'
% 'MaxUserVariation'
% 'MinCrossTalkRatio'
% 'Minimized'
% 'MontageChanId'
% 'Name'
% 'NotchCutoff'
% 'NoteLogView'
% 'NumDivisionsToCollect'
% 'OChans'
% 'OldLogChan'
% 'OnTimeline'
% 'Order'
% 'PhysElectrode'
% 'PhysName'
% 'PhysNum'
% 'PreTriggerDCOffset'
% 'PreTriggerTriggerDelay'
% 'PulseDuration'
% 'PulseIntensity'
% 'Range'
% 'Rate'
% 'RefElectrode'
% 'Reference'
% 'ReferenceSignalFrequency'
% 'ReferenceSignalP2P'
% 'Resolution'
% 'ResponseChime'
% 'RightDisplayGain'
% 'RollingWindow'
% 'SamplingFreq'
% 'ShowLiveTriggered'
% 'SignalType'
% 'SpecialType'
% 'SpectralEdge'
% 'SquelchThreshold'
% 'StartOnTestActivation'
% 'StimCtrlView'
% 'Stims'
% 'SwStimId'
% 'SweepsPerAvg'
% 'TestDirView'
% 'ThetaMax'
% 'ThetaMin'
% 'ThresholdDelay'
% 'Timebase'
% 'TimelineID'
% 'To'
% 'TriggerDelay'
% 'TriggerSource'
% 'TriggerToStimLat'
% 'TrueDifferential'
% 'Type'
% 'WaveformView'
% 'WaveformView 1'
% 'WaveformView 2'
% 'WaveformView 3'
% 'WaveformView 4'
% 'WaveformView 6'
% 'Width'
% 'WidthFraction'
% 'X'
% 'XFraction'
% 'Y'
% 'YFraction'

    
    
    properties
    end
    
    methods
    end
    
end

